### PR TITLE
Mistake generation

### PR DESCRIPTION
**Pull request by ben2002chou**
merge

### CODE REVIEW

**Comment by ben2002chou** [comment]
done

**Comment by lukewys** [comment]
Hey ben, I noticed you created and deleted some pull requests. I checked and found some of them are format and docstring update. If you are comfortable with it we could also merge your change of code formatting to this codebase.

**Comment by ben2002chou** [comment]
Hi, this was meant for my own fork. Sorry for the inconvenience. I will submit a better version of the code changes in the future, but this code change is currently unstable which is why I deleted it.

**Comment by lukewys** [comment]
No worries! Good luck with your project!

Ben Chou ***@***.***> 于2024年2月27日周二 12:13写道：

**Pull request closed without merging**
